name: sipm-analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3
  - matplotlib>=3.4
  - seaborn>=0.11
  - scikit-learn>=1.0
  - h5py>=3.1
  - pyyaml>=5.4
  - tqdm>=4.62
  - jupyter
  - notebook
  - ipywidgets
  - pytorch>=2.0
  - torchvision>=0.15
  - pip
  - pip:
      - xgboost>=1.5.0
      - PyWavelets>=1.1.1
      - shap>=0.40.0
      - joblib>=1.1.0
